### ISSUE TITLE
Make Walrus Kick require to be lvl 3. 

### ISSUE THREAD

**Issue by darklordabc** [LegendsOfDota/LegendsOfDota#328]
![image](https://cloud.githubusercontent.com/assets/16277198/15801197/918bdb60-2ad0-11e6-8616-c8846aebbd05.png)
![image](https://cloud.githubusercontent.com/assets/16277198/15801208/db08c000-2ad0-11e6-953b-651d1d3e2715.png)
![image](https://cloud.githubusercontent.com/assets/16277198/15830484/ecc61be4-2c5b-11e6-89d0-6fd23f7375b8.png)

I know Walrus kick is a controversial issue, but I think its about time we do something about it. 
Its broken (not adhering to melee range), very powerful and seems to be ruining the game for people on a semi-regular basis. 
Simple solution is too make it require level 3, like Divided we stand, so that players can have some breathing space, a few levels and items before they start getting destroyed from 600 range and wondering what just hit them. 
I'll make a pull request, and @ash47 can decide after the discussion here. 

@TheRisen41, @vaxxvirus, thoughts?

**Comment by TheRisen41** [comment]
Yes i agree it is totally op for a lvl 1 ability. No other ability can compare in terms of dmg and impact at lvl 1. But i think it should be skillable at level 4 because it is simpy as strong as a level 4 ability. Another option is to make it scale.

**Comment by darklordabc** [comment]
The reason I went with lvl 3, because there is some precedent with that with divided we stand, does any ability unlock at lvl 4?

**Comment by TheRisen41** [comment]
No there is no ability that is enabled at lvl 4. What i mean is if you compare it to other non ultimate skills it behaves like a lvl 4 ability. Even then it only requires one skill point.

**Comment by darklordabc** [comment]
Oh yes I see what you mean now.

**Comment by vaxxvirus** [comment]
It doesn't much bother me, what confuses me along with Eyes in the Forest is that these abilities aren't level 6 buys like ultimates. Still, I agree. It's stronger than it should be at level one.

**Comment by ash47** [comment]
https://github.com/ash47/LegendsOfDota/pull/329

**Comment by darklordabc** [comment]
Poll: Should Walrus kick require lvl 3? Thumbs up this post for yes, thumbs down for no and to leave it alone. Mobile users switch to desktop view on bottom right to thumbs comments. 
@vaxxvirus @TheRisen41 @ash47 @jimmydorry @paralin @Jexah @Myrl

**Comment by paralin** [comment]
why am i tagged in this

**Comment by ash47** [comment]
Because that dude has no idea who you are

**Comment by darklordabc** [comment]
You were one of the few people that come up when you press @. Sorry,  thought you were associated with this repistory.

**Comment by Jexah** [comment]
Implying each person's opinion has the same value.

**Comment by jimmydorry** [comment]
Indeed, the weight of my votes should clearly be 10 votes.

/unsubscribe

**Comment by ash47** [comment]
The weight of my vote is 100% as I'm the only one with write permissions lel

**Comment by darklordabc** [comment]
Level 3 is already a compromise from level 6, level 2 is an improvement but I don't think it goes far enough in nerfing its abuse power. Level 2 is achieved like right after the first creep wave.

**Comment by Jexah** [comment]
Level 6 was never, ever on the table. It would destroy the purpose of the ability. The fact that level 2 is reached after the first creep wave is the entire point. The skill retains its strength but can't be used to contest level 1 rune. 

I've never lost to the skill, so it can hardly be OP. It doesn't scale at all, the four points invested in Walrus Kick and 6 all stats in my opinion is very low value in the mid to late game.

**Comment by darklordabc** [comment]
>Getting this ability at level 6 will destroy its purpose.
That's obviously not true, as in original dota your hero doesn't get it till at least lvl 10.
>Cant be used to abuse rune.
Players are having difficulty with this ability, not just at the rune spot. Solving just the rune spot harassment is only dealing with a part of the problem. 
>I've never lost to it so its fine
But lots of people are complaining about it, so its obviously a problem for a few people. As one commentator said its a 350 nuke with 8 second cooldown in the early laning stage, where heroes have around 500/600 hp. And its usefulness late game is redundant if the enemy team has already left because they were getting two hit from 600 range and dying.

**Comment by ash47** [comment]
Poo bars

**Comment by darklordabc** [comment]
You really think getting destroyed in 2 hits from a spell with a broken range, 2 minutes into the game, should be part of the LoD experience?

**Comment by darklordabc** [comment]
"4 points invested in Walrus Kick"
You realize its a 1 point ability right? Its the highest damaging lvl 1 ability in the game (second only maybe to illuminate).

**Comment by Jexah** [comment]
Are you legit an idiot or being intentionally ignorant? Trying to draw power parallels between Dota and Legends of Dota is just plain useless.

If the enemy team leaves, then they deserve to lose. Abandoning is among the biggest offences in Dota 2. Once somebody regularly leaves games, no matter the circumstances, they void their privilege to have an opinion on LoD.

If you are playing against a Lina in Dota 2, and never move, and you get combo'd and die, you blame Valve for making Lina imbalanced and able to kill any hero in two combos (without ult).

Adjust your play if you're playing against a build that is strong early game. If your build is not as strong early game, then it's either shit, or designed to peak later on in the game. Use that to your advantage by playing around the player/s with Walrus Kick, and late game you will destroy them.

If you have any new information, please feel free to follow up, but if you're going to regurgitate anything you've already said, or parrot opinions from people who rage quit, bitch, and cry, without actually doing a detailed analysis of the skill, then don't even bother following up.

You clearly can't read. I said "four points invested in Walrus Kick and 6 all stats" explicitly stating that with the four points you'd spend on a normal skill, you'd spend one point in Walrus Kick, and 3 in stats, thus at the mid to late game, the four points for that slot have netted you 6 all stats and Walrus Kick. Sure you get Walrus Kick at level 1, but I wasn't referring to the early game.

**Comment by darklordabc** [comment]
"Adjust your play to deal with an OP ability" is a cop out.
If the only way to counter an ability is to avoid that hero at all costs, than the ability is clearly OP. And its not a "build" that is op early game, its a single ability. You could go a late game build and get Kick just to ensure early game dominance.
Most casual players are not going to "adjust" there play, there going to go lane, get half their half removed from an unknown spell at 600 range, 8 seconds get hit again, killed and quit.

**Comment by darklordabc** [comment]
The aim here is to make an enjoyable game. This ability is clearly ruining the game for a lot of casual players in a map mode designed for casual players, saying "screw them they can just learn to adapt" is a pretty lackluster response as a game designer.

**Comment by Jexah** [comment]
If they don't adjust their play, then they lose. Just like in Dota 2. Tough.

A better player beating a worse player is pretty standard stuff. Like I said before, if the people you're getting these complaints from are players who just abandon after they give first blood, then their opinion is void. I'm not designing an Angry Birds clone. I built LoD for myself because I enjoyed playing it. Ash took over because he enjoyed playing it and I had to take a break. The game was designed with two pillars in mind. "I must enjoy playing it" and "it must be balanced". I don't care what somebody who is terrible at the game has to say. The game isn't balanced for terrible players.

The only reason we originally accepted feedback from players is because there were things that we missed, that other players noticed. Bugs, interesting interactions, etc. We take the information they've given us regarding facts and mechanics, not feelings or opinions, and then we make a decision based on that.

Walrus Kick is literally crap compared to the vast majority of OP combos and skills. The OP skill bans are reserved for things that are OP across the board. If somebody doesn't like a skill, they have 10 chances to ban it. If 10 players choose not to ban it with 100 total bans, then clearly nobody gives a fuck about it. If bans aren't voted for, than the majority of players in that game wants to play specific skills, so be it.

I don't know what your obsession is with arguing. You're like an angsty teenager who believes they own the world. We are aware of the skill, we know how powerful it is, and I've told you where we stand. We are considering changes to the skill, that's more than you have the privilege to ask for. The most you can do is bring it to our attention, but bothering us, arguing with us, and just generally being a dick is not helping anybody.

I feel it's pretty rich that you're judging the designer of a mod, when you yourself after years of hiring devs to make your games on Reddit, still haven't come out with a dime. In fact, do you even have a game to speak of? If you want to make a mod, go make a mod, don't hijack an already successful mod.

If you have any ideas, feel free to share. If you have any questions or concerns, feel free to share. Don't argue, don't be a dick, and don't excessively bother us; we have real jobs. The decisions about what happens to LoD are ours and ours alone. Thanks for bringing Walrus Kick to our attention.

**Comment by darklordabc** [comment]
Sorry I was under the impression Ash47 was the sole admin for this project, if i knew your opinion was final I wouldn't bother debating thr point so much.

**Comment by Jexah** [comment]
He is the sole admin, but he has already told you he takes direction from me in regards to design in the last thread where you did this.

**Comment by ash47** [comment]
Who's not debating? The issue is still open at this stage. If I had enough,
I would have locked the conversation and closed the issue.

Jexah is like the "coadmin" (He plays a lot more than me, and he is my
expert when it comes to balancing stuff / trying new stuff), I'm just too
cheap to pay for an organization, and as such, he doesn't get an official
title.

Jexah has been a part of this mod since BEFORE the first version, he
literally contributed code to the original version almost 3 years ago,
rough parts of his code are still in this.

**Comment by darklordabc** [comment]
Well what do you think Ash? You think Walrus Kick is fine as it is?

**Comment by ash47** [comment]
I think I'm more focused on the bigger picture, doing shit that's actually
important, trying to handle rolling out an update

**Comment by Myrl** [comment]
@ash47 FOSS organizations are free.

**Comment by ash47** [comment]
:O

**Comment by Myrl** [comment]
@ash47 From the [create an organization page](https://github.com/account/organizations/new). 

> Unlimited members and public repositories for free.

**Comment by Snoresville** [comment]
darklordabc i think you need to stop whining about pretty much the things that you dont like

**Comment by darklordabc** [comment]
Whining about things that are bad for LoD and the player base*. FTFY

**Comment by vaxxvirus** [comment]
You guys, don't be assholes. To anybody. This is why people are afraid to contribute here. He's discussing it and being met with serious aggression. My personal opinion? I don't care, I'd rather have hook or dragon tail for doing early work. 

Yes, it makes runes a huge pain in the ass and it does ensure you win the laning phase with the kick after kick with its relatively low cost. I'd still rather be against a kicker than someone who got Stone Form. Or Gyrocopter with some of the attack modifiers that translate to the gunner. Bottom line I think is that it's better than any other level one, and should be balanced a bit, but it's no game maker unless your enemies, allies, or you are children and can't handle spammy spells. 

Just don't be an asshole. It's just a game.

**Comment by vaxxvirus** [comment]
I'm an idiot with github and I know the dev is reading here, so I'll report a combo. Dispersion and Enrage aghs give 100% damage reduction, even versus pure damage. I played a game with my friend who used it as Keeper of the Light and he dove towers as soon as he got it, the whole game. I've tried it too. It's only me bringing it to light and I've no idea how to report it.

**Comment by ash47** [comment]
Lol, raise it in a separate issue, not someone else's issue

**Comment by Jexah** [comment]
@vaxxvirus There is a difference between bringing up an issue and spamming threads with the same arguments over and over, crying OP. If you act like an ass you'll get treated like one, not just in this thread but in the whole wide world.
