### ISSUE TITLE
dispersion + enrage = 102% dmg reduction

### ISSUE THREAD

**Issue by DankBudd** [LegendsOfDota/LegendsOfDota#367]
also goes over 100% with bristles passive and burrow. 
but bristle your only invincible on one side, they other is just regular enrage tankiness
and burrow.. your just a pile of dirt.
with dispersion and enrage you can fountain camp every 18 seconds with scepter (less with octarine)

vaxxvirus said something about this combo but he put it in the wrong place.

**Comment by Snoresville** [comment]
percentages dont work like that.
You take 1000 damage.
With the enrage buff, you reduce damage by 80%, which is 800
You are left with 200 damage
With the dispersion passive, you reduce that damage by 22%, which is 44.
You now take 156 damage, unaffected by armor and damage block.

I guess if you haven't done year 9 maths, you would think that dispersion and enrage would be an op combo

**Comment by Jexah** [comment]
#rekt #brutal

**Comment by DankBudd** [comment]
Yeaaah. 
You may think that's how it works, and it's honestly how I expected it to work. but go try it and see what happens. I'll even suggest some builds for you.
I can think of dozens of builds revolving around enrage +dispersion that could win the game with incredible ease.
Eziest one, just add life break. Take away a huge % of their max HP + the dmg you dispersed from life break self dmg. (Dispersion applies before all reductions so even though you take ZERO damage, you still disperse 22% of 65% of your max HP.) But this build wouldn't win you the game 1v5.

I'm guessing you don't actually Play LoD all too much, so I'll break this one down for you.
Let's go more oppie with:
Gyrocopter.  (We are getting scepter anyway, so. Free atks even when disabled)
-str essence  (gives infinitely increasing HP when paired with marksmanship and atkspeed)
-morph agility (since we are going to have 7k HP, who needs str? Free dmg and atkspeed)
-dispersion (, because who could say no to making the enemy hurt themselves when they hit you )
-enrage. (Temporary invincibility for whatever reason ex. Forcestaffed into fountain)
-marksmanship (not for the agi, for the scepter splitshot. Potential for 3x the str steal)
-infernal blade (you can splitshot -infernal blade, also hp burn + ministun is gr8)
With the gyro build you won't deal any damage outside infernal until scepter, but as soon as you get scepter you can 1v5 the enemy team inside their own fountain.

**Comment by Snoresville** [comment]
you're only accounting for the fact that respawn timers are close to or under 1 second. if it were, tank builds would be much better killing things in the fountain. you're also under the assumption that comboing split shot with infernal blade would be powerful, which in fact only the first person that either your normal attack or your split shot hits when infernal blade is off cooldown will be infernal blade'd.

I'll talk about life break with dispersion + enrage combo first.
Let both of the players have 500 hp each and considering that lifebreak does 65% of hp and the player doing the lifebreak has maxed dispersion and enrage, which is a 22% reduction before other and 80% damage reduction respectively.

The player lifebreaks the other with the enrage buff and maxed dispersion. The player dealt 65% of 500 hp as damage, which is
500 * 0.65  = 325 damage.
Considering the innate magic resistance to be 25%, this damage is lessened to 
325 * 0.75 = 243.75 damage dealt.
So the lifebroken player got hit and is left at
500 - 243.75 = 256.25 hp

but what about the dispersion damage?
considering that dispersion happens before enrage and the damage from dispersion depends on the damage type, which is magical because life break does magical damage.

500 * 0.35 = 175 self damage 
175 * 0.22 = 38.5 reflected damage
38.5 * 0.25 = 9.625 total damage considering magical resistance

With dispersion damage in mind, the lifebroken player now is left at
243.75 - 9.625 = 234.125 health
This is relatively small damage and you're better off with some ancient seal + decrepify combo.

but what about the player getting "literally no self damage" from life break?
175 - 38.5 = 136.5 damage because dispersion ignores damage
136.5 * 0.2 = 27.3 self damage
27.3 is around 5% of 500 health
It does prove your point that you take almost no damage from it, but it does not mean that life break and dispersion is a good idea.

now about the gyro build.
Gyro getting scepter would increase your dps, but remember that the side gunner does NOT proc on-hit effects like essence shift and marksmanship's split shot (lul)
You will be squishy as fuck if you choose to use morph agility and str essence, you're prone to random walrus kicks. Not popping enrage before you expect it would be 273 dealt (350 * 0.78), which is infact going to be about 75% of your hp gone considering you picked up a magic wand and str treads. They might go for a dagon with the money earned by killing your teammates and hand you over after that. You're better off with staying alive long enough to throw trucks of damage by getting normal essence shift with probably a flesh heap instead of str morph.
Enrage only lasts for 4 seconds, undispellable and makes you a real beast to reduce any kind of damage to around 16% of it after dispersion before armor. However, you're not immune to crowd control effects. Remember that there are people who can bash you while going at max attack speed and each bash can last up to a second, which is too long to idle in enrage. But you still have a side gunner right? well it wont proc on-hit effects anyway.
Marksmanship is alright. Same with infernal blade, but you cant do a simultaneous triple infernal blade with marksmanship.
The example gyro build needs to bend over to one side or another, if you don't go all the way towards one area like tanking or attacking, you can't compete within lod with that build and farming scepter is going to be very slow because you don't have any real skills that complement your damage.

to tank the fountain you must realise that the fountain does around 970 damage per second (from the wiki), and each second you would have died if not for enrage + dispersion, so lets see how much damage you get in the fountain.
0.156 (total damage multiplier with enrage and dispersion) * 970 = 151.32 damage per second.
On the next second, if you had morphed your agi to the point where you have no str and no health items, you die. This damage does not factor armor. I haven't even talked about how the fountain has essence shift that can remove health faster than you can triple time yours.
If gyro had no more than 600 max hp, gyro wont last the full duration of enrage, and even if he did, facing a shocking 756.6 dps after enrage is a big jump. But that's, as you said is an emergency button.

Going so far to claim that grabbing a scepter will let you fight a whole team with the set of abilities is outrageous if gyro doesn't even have health. and also expect damage other than physical as you can't rely on the armor from gyro for that.

My point is that your claims are really unsupported and circumstantial. To 1v5 an enemy team in the fountain would require that not only do you have to kill the enemy fast within 4 seconds, but you need to have the hp to do that and expecting the enemy to not have a stun of any kind (even bash) and also deal damage of a pea shooter.
also just remember that enrage and dispersion comboing together will give you 84% damage reduction, and one point to add 1 more % while enrage is on to dispersion feels like an unsetting investment.
You might not see that you are dealing damage, and maybe there's a guy playing enrage and dispersion who builds a vanguard and goes around whacking people and all of your teammates disconnect because he looks invulnerable, especially considering if he gets something like return, flesh heap and reactive armor, which is goddamn annoying and top it with chemical rage.

I have played lod many times, I can play a one punch vengeful spirit if i feel like it. and also if that combo reduces too much damage, why not go essence shift?

**Comment by Jexah** [comment]
Actually the fountain does about 1300 damage per second (Damage: 190-199, BAT: 0.15), before reductions.

Also, this is just the regular Dota 2 fountain, not the LoD fountain, which has Psi Blades and an MKB.

**Comment by ash47** [comment]
Legends of Dota fountain also has fury swipes, so it stacks damage for every attack :O

**Comment by DankBudd** [comment]
holy shit you trigger me so hard, half of your info is wrong, and you didnt even try the build.
im not talking about diving the fountain in theory, based on the numbers ive provided. im talking about actually doing it, hundreds of times across multiple game. 
im not talking about respawn timers being 1 sec, me going in and afking in fountain. i mean, walking into fountain, getting a rampage, and walking out.
im gunna go download something so i can make some gifs or something to prove my points.

**Comment by Jexah** [comment]
Looks like you were taking damage, though. Your HP was changing after you'd healed up to full. Honestly the fact that you needed level 25 and 6 slot to show this just proves my point further. Yes, there are many builds that can tank the fountain with 6 items and level 25, but by that point the game is already over. Most of my games end before the enemy reaches level 16.

The highlight of Gyro's gunner proccing Infernal Blade while it's on cooldown, and not putting it on cooldown is interesting, though.

**Comment by DankBudd** [comment]
>
 Looks like you were taking damage, though. Your HP was changing after you'd healed up to full. 
> 
not sure how to use quotes on here..maybe i did it right?
my max hp was changing because of str essence giving me more hp, i wasnt taking damage.

**Comment by Jexah** [comment]
Ah, sorry, I was viewing on mobile. You're right, although no damage for a few seconds isn't really out of the ordinary. At earlier levels and farm, stuns would ruin this build. Got no escape, dispersion is the only tank skill, etc.

All in all the Marksmanshot split + Infernal Blade is the only thing of concern here.

**Comment by DankBudd** [comment]
infernal blade has that interaction with a few skills. it seems pretty inconsistent, but the one pattern that it usually follows is that if infernal is on cd when a different ability trys to proc it(pa dagger, gyro scepter, marksmanship,etc), it will work. but if its not on cd, it will not.

**Comment by ash47** [comment]
Doesn't one of Oracle's abilities stop the player from taking damage for a
few seconds?

**Comment by DankBudd** [comment]
"Temporarily alters an ally's destiny, delaying any healing or damage taken until False Promise ends. Any healing that is delayed by False Promise is doubled. Removes most negative status effects and disables on initial cast." - wiki

**Comment by Snoresville** [comment]
hmm so apparently side gunner works with on-hit passives and looking at the dota wiki wont help me much within lod then, and that you could tank a fountain on enrage. 4 seconds is a real deal.
i still consider the build as a peashooter because as i said, there's no real abilities that affect right click damage in a way. dispersion and infernal blade made up most of the damage that was caused in the fountain and outside of the fountain, all you could do is hope that the enemy doesn't notice that you're trying to steal stats off them.
but hey, who knows? apparently the infernal blade is the only major damage component from the build itself and some people like to pick basher builds and similar that could lock you down earlier than you can build your aghs.
the one thing that you haven't showed in all of your gifs is the usage of morph. you stated that you would get free damage and more agi and the missing strength would be instead be gained from items and str essence shift, but however you haven't done that, which is important in your example where you try to kill people in the fountain. i know you think that it wont matter, because at the end you get more than a million strength killing them in the fountain provided that you are farmed with items, but if that's the case, why not swap morph out?
and also there are people running around with silver edge and split pushers, so dont expect your build to be universally op, it's not about killing the most players, it's about the objective. even if enrage + dispersion worked as a pseudo self guardian angel, how would you win if your other teammates vary in intellectual quotas?
anyway, back on whether dispersion + enrage is a troll combo, no it's not. it's only op if enrage is popped and only lasts for 4 seconds. it's like saying ravage + blackhole is op because you could stun a whole team for up to 6.8 seconds. these two abilities have long cooldowns for a reason

**Comment by iprobie** [comment]
any tank builds can deal decent damage with just life break aghs, plus it's a great gap closer. oh and self-damage from life break is also reduced by dispersion (and consequently dealt to nearby enemies).

countered by bashes and ess shift on ranged ofc or crap like decay + witchcraft.

on topic: I won't consider it a troll combo. I've seen a lot more obscene combos rather than taking no damage at all (if you get fountain camped, it's your fault or the lobby has retarded settings such as near 0 respawn time).

**Comment by DankBudd** [comment]
yeah, you're right, i did forget to showcase the morph agility. if you want, i could show it off, but all it does is increase my damage/attackspeed by about 60 each at level 25.
but i never said my build was universally op. i said you could 1v5 in the enemy fountain with it, which you could infact do.
if i wanted a build that could win in any game, id do a build with vengeful spirit (or gyrocopter if grow is unbanned) and morph agi.
with rat skills like demolish (and demolish) and/or grow, furion tp, refraction (to help tank with agi morph), focus fire, and if the respawn times were high, maybe even suicide squad for the 50% respawn... theres too many skill combinations to rat with off the top of my head.
its not too difficult to use furion tp when no one is around to stop you and backdoor their base.

oorr if i wanted to be fancy, id get infernal blade with marksmanship and attack a lone creep near the tower to infernal blade the tower

rat doto, best (actually worst) doto.

**Comment by Jexah** [comment]
So... What's the purpose of this thread if you don't think the combo is OP?

**Comment by ash47** [comment]
I just marked it as OP, we'll see how it goes, stats suggest most people dont even use the "troll combos" blocking list anyways, so, meh
