### ISSUE TITLE
Add possibility to change time of banning phase in custom mode and reduce it in AP mode to 30 sec

### ISSUE THREAD

**Issue by LODonly** [LegendsOfDota/LegendsOfDota#372]
Please add possibility to change time of banning phase in custom mode and reduce it in AP mode to 30 sec (or make a voting what ti,e is better for banning phase). Current default time is too much for banning in ap mode.

**Comment by ash47** [comment]
It's not too much, how long do you think the banning phase goes for?

**Comment by LODonly** [comment]
Currently it's 90 sec after 1st player finishes banning. So I suggest reduce it to 30 sec. Anyway it will take also some time for banning, I just propose reduce waiting time.

**Comment by ash47** [comment]
No it's not. The 90 seconds is lowered based on the percentage of people
who are done, if it takes the full 90 seconds, it means people need more
time. If everyone presses ready fast, it can be done instantly, so, it's
only you who wants less time, everyone else is using the time or needs more
time
On 2 Jul 2016 5:07 AM, "LODonly" <notifications@github.com> wrote:

Currently it's 90 sec after 1st player finishes banning. So I suggest
reduce it to 30 sec. Anyway it will take also some time for banning, I just
propose reduce waiting time.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/LegendsOfDota/LegendsOfDota/issues/372#issuecomment-230025487>,
or mute the thread
<https://github.com/notifications/unsubscribe/ADlKDvg3gvgsozN9RT-rTh7f7peNNDn_ks5qRWWFgaJpZM4JC99s>
.

**Comment by ash47** [comment]
Nothing has happened in this discussion for a while.
