### ISSUE TITLE
Make Walrus Kick have multiple levels?

### ISSUE THREAD

**Issue by Njol** [LegendsOfDota/LegendsOfDota#383]
Just an idea, but what if we make Walrus Kick a normal ability with 4 levels? Each level could increase the damage, push distance, and/or slow, ending at the current values at level 4.

Similar goes for Burrow, Assimilate, and the neutral Fireball.
Maybe also Eyes in the Forest (for example reduce CD or increase mana cost at lower levels).

Also maybe make some neutral abilities that are pretty crappy right now (Slam, various auras, Heal, Thunder Clap, Shockwave, Mana Burn, Hurl Boulder, etc.) also have 4 levels, where the current version is like level 1 or 2, and level 4 makes it as strong as hero abilities.

If you think this is a good idea I can do it myself and then bother you again once i'm done :wink:

**Comment by LODonly** [comment]
In my opinion it's better to make it available from 6 lvl

**Comment by ryanwilson112** [comment]
In my opinion although it's OP early game it just falls off super fast. 

I've played several lobbies with a streamer where initially it was a house rule to not pick it, but we started to notice the teams who had a Walrus Kick lost more often than not. Because that's a useless skill late game and you're basically fighting 4 vs 5. So it's now fully allowed if that's the build you want to go. 

Level 6 is about when it falls off and is useless to have I reckon. Because by then the carries have their markmanship and are hitting hard, or the tank have their huge regen from alch rage.

The best nerf to it is to make it available from level 2 onwards. So there's not instant rune kicks or first wave kicks. At least then you're given the first wave / level, and have a bit more time to realise they have it and play with caution in lane.

**Comment by Njol** [comment]
If you think it's bad and those you see with it are bad, it's just because they have no idea how to play:

early game: its low CD means you can completely dopminate the early game, which basically means you win the game
early/mid game: it's a strong nuke (350 damage) _which only requires a single ability point_, which is extremely useful if you have 6 abilities to spend points on - for example you can have 2 nukes while someone else only has one.
end game: it pierces spell immunity, so you can just kick away the enemy carry and wait for their bkb to time out, get away yourself, or kick away one enemy and fight two 1v1 instead of one 1v2.

**Comment by ryanwilson112** [comment]
> dominate the early game, which basically means you win the game

Objectively untrue in every single game of Dota 2 ever played. "Basically" is an understatement and a half. There's soo, soo many ways a team can easily comeback in a game and take the advantage. Even in a single team fight. 

This is something we've discussed tons before. The conclusion seemed to be nothing was done. 

All i'm saying is from personal experience I've played dozens of games with Walrus Kick and it's ass late game and loses more often than win. If your build's late game benefit is "to kick away the enemy" then so be it. Perhaps pick up a ability that turns that "we don't want to fight" into a "we can get a kill here" instead of abandoning the concept.  

The "strong nuke" is weak against tanks, you're probably dealing more damage to yourself, the carries shred half your hp and then you're using it escape, best case scenario. Worst you're bashed and you die before the kick is pulled off. Or they survive the "strong nuke" and you've returned them back to their team or tower. 

Dismissing poor win rate in personal experiences as simply "They don't know how to play" is a poor excuse that works both ways. If your carry build with walrus kick can beat two other carry builds without kick, then they're the ones "who don't know how to play". I'd need to see it to believe it basically. On that note, I haven't seen a Walrus Kick actually contribute anything late game besides saving yourself/team from dying to an enemy carry. It's always used to aid escape or to make a team fight 4vs5. And if you're losing a 5vs5 without using Walrus Kick, then there's something wrong. Probably you, since you've got a skil that helps the enemy escape. Otherwise if you're winning you don't want to kick, since you're letting one of them escape. Relying on a kick to make it 4vs5 could simply be a cyclone instead. Or an AOE stun to turn the tide. 

That's my two cents anyway. I agree it needs a small nerf to level 2, but level 6 has and never will be a consideration. It wasn't last discussion. Your suggestion to add in multiple levels is new but I remain confident all it needs to balance early game is to allow the first wave and 00:00 ruin contest. I'm completely fine with it not being changed either, since it's so shit late game. Letting them have those level 1 kicks will be the only time they're relevant in the game so nerfing it further might be too cruel.

**Comment by Njol** [comment]
Actually I usually combine Walrus Kick with Fireball for an easy early game (easy kills and easy farm as soon as level 2), and use Mystic Flare, Multicast, and Burrowstrike with Scepter for late game (even tanks rarely survive a 3x multicast Mystic Flare for more than 2-4 seconds). And if I'm surprised while Burrowstrike is on cooldown, the enemy has BKB, or my Flare didn't kill them completely, I just kick them away (when playing as pugna it has 600 cast range which is usually sufficient), while being able to fight in less than 10 seconds with my full damage output again.

I rarely play carry since it requires that your team is not completely crappy, which it unfortunately is like 30% of the time, and i'm just not willing to risk that anymore.

**Comment by Jexah** [comment]
That's the spirit Njol, assume your team is shit and your winrate will go up, that's what I do.

> That's my two cents anyway. I agree it needs a small nerf to level 2, but level 6 has and never will be a consideration. It wasn't last discussion. Your suggestion to add in multiple levels is new but I remain confident all it needs to balance early game is to allow the first wave and 00:00 ruin contest. Making it available at level 2 onwards was a suggestion from the last time this was brought up I agreed with, not mine.

I think this was originally my idea, and I agree with most -- if not all -- of what Ryan has said in this thread. The only point I'd question is the one about having a bad team. 

> Dismissing poor win rate in personal experiences as simply "They don't know how to play" is a poor excuse that works both ways.

When playing builds that only shine when your team members are decent, losing comes standard, and you can blame your team, but consistently falling in to the trap of expecting your team to be good, makes you bad, as weird as it sounds. A good player would adapt to the fact that they regularly get bad teams, and pick builds that can carry themselves, like what you said you did, Mjol.

**Comment by ryanwilson112** [comment]
> Walrus Kick with Fireball for an easy early game (easy kills and easy farm as soon as level 2), and use Mystic Flare, Multicast, and Burrowstrike with Scepter for late game 

That actually sounds like quite a fun build, thanks for sharing! I'll probably try that out next time I play. Blademail must be your archenemy though. You could literally teamwipe them all, they wait 120 seconds and respawn, buy blademail, and your Mystic Flare would still be going on because it's fucking so long and they'd kill you. 

> Similar goes for Burrow, Assimilate, and the neutral Fireball.
Maybe also Eyes in the Forest (for example reduce CD or increase mana cost at lower levels).
Also maybe make some neutral abilities that are pretty crappy right now (Slam, various auras, Heal, Thunder Clap, Shockwave, Mana Burn, Hurl Boulder, etc.) also have 4 levels, where the current version is like level 1 or 2, and level 4 makes it as strong as hero abilities.

We haven't touched on these yet.
I don't think any of these see use nearly as much as Walrus Kick does. Maybe I just don't know the pub meta right now. 

The only one I can claim to have seen use at level one and probably the most used one here is Eyes In the Forest and I think the inherent trap that ability has is that the users feel like they need to go ward the jungle with it or that they go full support. So they miss out on exp. It's also got a long enough cooldown and mana cost as it is.

Burrow seems like a weird one, i'm not sure what you'd change on this. I haven't seen it used often but it might be something I try out later. 

Assimilate is another one of those skills that relies on having a good team. I will admit, i'm one of those bad players who were assimilated and didn't pop out as soon as I was told to via a yelling man on coms. I don't think it's that great either even as a level 1 ability, as it's cooldown is pretty big. A blink, stun, assimilate build might be good with a good team though. Not sure how well it scales. 

In regards to the neutral skills, i'm against changing them. I think they should stay as weak / strong as they are. It feels more natural that way, I dunno. We've already buffed some of them, including Archer's Aura by giving it a 4th level, but I think that was only because having a non-ult level 3 skill would've been weird. But generally they're ony seen use in weird Neutral only lobbies which the impactfulness of your abilities are generally seen to be low so it's more about stats or item choice. 

Although I do agree Slam needs changed / fixed if possible, it doesn't scale the same way it normally does with Roshan and I think that would be cool if it worked as intended.

**Comment by Snoresville** [comment]
how about you leave walrus kick as it is because it's a value point, and then you watch the other 4 players farm so hard they will beat your ass and you can't really try to kick them while getting wrecked by the other three people?

**Comment by applevac** [comment]
> Burrow seems like a weird one, i'm not sure what you'd change on this. I haven't seen it used often but it might be something I try out later.
Burrow is a very, very strange spell. The regen & damage reduction would make you think that it'd be good for a tank build, but the spell casting capability usually makes its way into casters' builds. It's very easily countered by dust and gems (wards aren't all that great if they have a blink--they leave pretty quickly). I really don't think it needs balancing at all, because, as potent as it is, it's just another invis spell.

I wonder how a tank build containing it would work. Assuming they have burrow and dispersion, and that they don't stack additively (they probably trigger at different points), they would only take 46.8% of the damage. Also, can you manually use autocasts and/or arcane orb to attack when normally not allowed to attack while burrowed? So many questions!

**Comment by ryanwilson112** [comment]
> Burrow is a very, very strange spell. The regen & damage reduction would make you think that it'd be good for a tank build, but the spell casting capability usually makes its way into casters' builds. It's very easily countered by dust and gems (wards aren't all that great if they have a blink--they leave pretty quickly). I really don't think it needs balancing at all, because, as potent as it is, it's just another invis spell.
I wonder how a tank build containing it would work. Assuming they have burrow and dispersion, and that they don't stack additively (they probably trigger at different points), they would only take 46.8% of the damage. Also, can you manually use autocasts and/or arcane orb to attack when normally not allowed to attack while burrowed? So many questions!

I just finished a caster game of burrow and the regen is insanely good. You don't need essence aura even. But as you say, any vision and i'm dead. The damage reduction is good and all, but what's the point if you're rooted/disarmed taking more damage than you're healing? You're a caster with like 2 strength regen going aghs for burrowstrike, this is greedy as fuck and easy to punish. 

So I did actually think about a tank build with it. If you use strength morph, you should regen a ton of health. So it might make a good return tank for example. You could burrowstrike into tower views and let them kill themselves. 

In hindsight though, neutral Fireball is really good early game farm and harass because of that cast range. So i'd nerf that to a level 2 pick-up also.

Agreed it's pretty balanced as it is.

**Comment by applevac** [comment]
Thinking about that tank build, apparently dispersion is banned with burrow. That's a disappointment. Strength morph could be incredibly good, though.

**Comment by ash47** [comment]
I actually did this.
