### ISSUE TITLE
 I am sick of this black hole

### ISSUE THREAD

**Issue by SyndromeDayna** [LegendsOfDota/LegendsOfDota#388]
The last few days in every game someone takes Tempest Double+Black Hole+Refresher.
Then this guy uses Refresher+Tempest Double while his clone is casting Black Hole.
This results in eternal Black Hole.

**Comment by DankBudd** [comment]
when you said eternal black hole, i thought you meant the game bugged out and had a black hole going on forever. but i cant replicate that by doing what you've said.

so i guess you just mean it lasts a long time because they have 3 black holes.
i dont know if this deserves to be a troll combo, it can only be done once every 200/180/160 seconds

**Comment by SyndromeDayna** [comment]
> Dota 2 Update - July 6th, 2016
> 
> Fixed a bug with the auto-select summoned units option, when resummoning Lone Druid's Spirit Bear and Arc Warden's Tempest Double.
> 
> Fixed a bug with Rubick's Spell Steal and stealing abilities with multiple states (for example, Timbersaw's Chakram).
> 
> **Fixed a bug with channeled abilities not ending correctly when Rubick's Spell Steal duration expires and when Arc Warden's Tempest Double is resummoned.** 

fixed by volvo

**Comment by ash47** [comment]
Added this as a troll combo to combat this

**Comment by SyndromeDayna** [comment]
> Added this as a troll combo to combat this
No, don't add it. Volvo fixed this bug.

**Comment by ash47** [comment]
too late ggwp, will roll back FML later

**Comment by ash47** [comment]
i guess this is fixed?
