### ISSUE TITLE
Voting System suggestion

### ISSUE THREAD

**Issue by AceHank** [LegendsOfDota/LegendsOfDota#408]
With the recent update of the voting system, I really liked it, especially the balance teams option. Before this is featured in LOD, a lot of people actually enjoying playing LOD from zero to hero. But now, since you can vote for extra gold/exp right from the start, a lot of people actually wanted to play it like that. And that is not fun. It could still be fun if the one that vote accepts whatever the result is. And a lot of people leave the game right away if their vote is disapproved. Now that's game ruining.

And my suggestion is, give a maximum for how much gold/exp can be given. So the game can be fun for both parties.

Because if they want to play with 1000000 starting gold/exp, they can play custom map instead.

Thanks

**Comment by ash47** [comment]
What max do you suggest? I am also considering changing it to 50% + 1 votes
to pass

**Comment by Jexah** [comment]
I think All Pick should only have votes for changing team etc, no actual game setting changes.

**Comment by ash47** [comment]
I think the point of all pick was mostly for a fast start, what's the logic
behind limited players from creating votes is that's what they want to do?

**Comment by Jexah** [comment]
I'd always assumed it was for a fast start in a reasonable mode, not necessarily balanced if there are no bans, but reasonable. Maybe if you want custom games to be fast, maybe enable all the votes in custom and get rid of the options picking at the start, so that people can get into the game faster, much like AP, and it leaves AP free for players who don't like retarded rulesets.

**Comment by ash47** [comment]
Issue is most options relate to picking so can't change them after picking

**Comment by AceHank** [comment]
Max gold 3000, enough for boots and one early item only
Max exp until you can get from level 1 to 6 (I don't know the exact number).

I'd definitely aggree with the 50% + 1 votes.

And I also aggree with Jexah. If you want to change the game setting, should play custom map instead of all_pick 6.

**Comment by LODonly** [comment]
AP mode is for fast start. That's why I had created topic about reducing ban time and bans quantity for ap mode because of it's low popularity at voting. Currently there are some too OP builds for AP mode. I have nearly 97% winrate at one build. 
And that's why too complicated voting system makes impossible to start game fast.
